# Your personal GitHub token
github_token: <your-personal-github-token>
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

# Guest OS timezone
timezone: Europe/Madrid

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: testnet

# Forwarded ports
gateway: 80
gateway2: 443
monitor: 8443
constellation_first: 9000
constellation_last: 9010
geth_whisper_first: 21000
geth_whisper_last: 21010
rpc_external_first: 22000
rpc_external_last: 22010
ethstats: 3000
block_explorer: 8888
block_explorer_api: 8080

# Project folder
projectfolder: "."

# Domain name
domain: testnet

# Virtual machine CPU cores number
# cpus: 4
cpus: 3

# Virtual machine RAM
# memory: 4096
memory: 6144

# Define which test-environment commit to use. Recommended last documented "stable one"
commit: "DEFINE_A_COMMIT"

# Ubuntu version. Uncomment the line containing the version you want to use.
ubuntu: "bento/ubuntu-20.04" #For Ubuntu 20.04 LTS
# ubuntu: "bento/ubuntu-18.04" #For Ubuntu 18.04 LTS